"""The host envelope: what this machine is, and how many research lanes it may run.

`detect()` never raises. Every probe that cannot answer falls back to a documented
conservative value, so an unfamiliar or half-instrumented host yields a small, safe
plan instead of an error, and the answer is written to `envelope.yaml`.

The plan is derived, not measured:

    live_colocated   the `live` stage of `portfolio.yaml` carries at least one strategy
    reserved         2 cores and 8 GB when colocated, else 1 core and 4 GB
    cores_per_lane   2
    mem_per_lane_gb  max(4, 1.5 x the largest baseline peak memory recorded over runs)
    lanes            max(1, min((cores_total - reserved_cores) // cores_per_lane,
                                (mem_gb - reserved_mem_gb) // mem_per_lane_gb))

`[env] reserved_cores`, `reserved_mem_gb` and `cores_per_lane` in `kanso.toml` override
the first three. The floor of one lane means a host too small for the formula still
researches, one card at a time. `mem_per_lane_gb` is rounded to two decimals before
`lanes` is computed, so the numbers written to the file reproduce the lane count.

Before the first baseline card there is nothing to calibrate against and
`mem_per_lane_gb` is its 4 GB floor; re-detecting after a baseline may change `lanes`.
The baseline peaks are read out of `state.db` with a read-only connection: detection
observes state and never writes it.
"""

from __future__ import annotations

import importlib.metadata
import math
import platform
import shutil
import sqlite3
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from kanso.env import host
from kanso.env.wheel import wheel_ok
from kanso.errors import ValidationError
from kanso.schemas.envelope import Detected, Envelope, Plan
from kanso.schemas.yamlio import dump_yaml, load_yaml

if TYPE_CHECKING:  # pragma: no cover - kept out of the runtime import graph
    from kanso.workspace import Workspace

FILENAME = "envelope.yaml"
HEADER = "# envelope.yaml — GENERATED by `kanso env detect`; do not edit.\n"
REMEDY = "re-run `kanso env detect`"

CORES_PER_LANE = 2
MIN_MEM_PER_LANE_GB = 4.0
BASELINE_HEADROOM = 1.5
RESERVED_COLOCATED = (2, 8.0)
RESERVED_ALONE = (1, 4.0)


def plan_for(
    detected: Detected,
    *,
    live_colocated: bool = False,
    reserved_cores: int | None = None,
    reserved_mem_gb: float | None = None,
    cores_per_lane: int | None = None,
    baseline_peak_mem_gb: float | None = None,
) -> Plan:
    """Derive the lane plan. Pure: the same inputs always give the same plan.

    A `None` override takes the default for its field. Overrides are clamped to what
    the formula can use — a reservation is never negative and a lane always gets at
    least one core — so an implausible `kanso.toml` yields a small plan, never a crash.
    """
    default_cores, default_mem = RESERVED_COLOCATED if live_colocated else RESERVED_ALONE
    cores = max(0, default_cores if reserved_cores is None else reserved_cores)
    memory = max(0.0, default_mem if reserved_mem_gb is None else reserved_mem_gb)
    per_lane_cores = max(1, CORES_PER_LANE if cores_per_lane is None else cores_per_lane)
    per_lane_mem = MIN_MEM_PER_LANE_GB
    if baseline_peak_mem_gb is not None:
        per_lane_mem = max(per_lane_mem, BASELINE_HEADROOM * baseline_peak_mem_gb)
    per_lane_mem = round(per_lane_mem, 2)
    by_cores = (detected.cores_total - cores) // per_lane_cores
    by_memory = math.floor((detected.mem_gb - memory) / per_lane_mem)
    return Plan(
        live_colocated=live_colocated,
        reserved_cores=cores,
        reserved_mem_gb=memory,
        cores_per_lane=per_lane_cores,
        mem_per_lane_gb=per_lane_mem,
        lanes=max(1, min(by_cores, by_memory)),
    )


def detect(ws: Workspace | None = None) -> Envelope:
    """Detect the host and derive the lane plan. Never raises.

    Without a workspace the plan uses its defaults and free space is measured at the
    current directory; with one it reads the `[env]` overrides from the configuration,
    the `live` stage from `portfolio.yaml` and the recorded baseline peaks from
    `state.db`.
    """
    facts = host.facts()
    compatible, _detail = wheel_ok()
    detected = Detected(
        os=facts.os,
        os_version=facts.os_version,
        arch=facts.arch,
        chip=facts.chip,
        cores_perf=facts.cores_perf,
        cores_eff=facts.cores_eff,
        cores_total=facts.cores_total,
        mem_gb=facts.mem_gb,
        disk_free_gb=disk_free_gb(_root(ws)),
        on_ac_power=facts.on_ac_power,
        python=platform.python_version(),
        nautilus_version=engine_version(),
        nautilus_wheel_ok=compatible,
    )
    reserved_cores, reserved_mem_gb, cores_per_lane = overrides(ws)
    return Envelope(
        detected=detected,
        plan=plan_for(
            detected,
            live_colocated=live_colocated(_path(ws, "portfolio.yaml")),
            reserved_cores=reserved_cores,
            reserved_mem_gb=reserved_mem_gb,
            cores_per_lane=cores_per_lane,
            baseline_peak_mem_gb=max_baseline_peak_mem_gb(_path(ws, "state.db")),
        ),
        detected_at=_now(),
    )


def write(ws: Workspace, env: Envelope) -> Path:
    """Write `envelope.yaml` into the workspace and return its path.

    The file is written beside itself and renamed into place, so a daemon reading it
    while detection runs sees either the old envelope or the new one, never half of one.
    It opens with the line that tells an operator the file is generated.
    """
    path = _root(ws) / FILENAME
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(HEADER + dump_yaml(env), encoding="utf-8")
    temporary.replace(path)
    return path


def read(ws: Workspace) -> Envelope | None:
    """Read `envelope.yaml`, or `None` where the workspace has none.

    A file that exists but is unreadable, is not YAML, or does not match the envelope
    shape is an error rather than a missing envelope: the file is generated, so a broken
    one means something overwrote it, and silently re-detecting would hide that.
    """
    path = _root(ws) / FILENAME
    if not path.exists():
        return None
    try:
        return load_yaml(Envelope, path)
    except ValidationError as exc:
        raise ValidationError(exc.message, exc.remedy or REMEDY) from None


def live_colocated(portfolio: Path | None) -> bool:
    """Does the `live` stage of `portfolio.yaml` carry at least one strategy?

    A workspace without the file, or with one that says otherwise, is not colocated:
    the plan then reserves the smaller share for whatever else runs on the machine.
    """
    if portfolio is None:
        return False
    text = host.read_file(portfolio)
    if text is None:
        return False
    try:
        document = yaml.safe_load(text)
    except yaml.YAMLError:
        return False
    stages = document.get("stages") if isinstance(document, dict) else None
    live = stages.get("live") if isinstance(stages, dict) else None
    strategies = live.get("strategies") if isinstance(live, dict) else None
    return isinstance(strategies, list) and len(strategies) > 0


def max_baseline_peak_mem_gb(db: Path | None) -> float | None:
    """The largest baseline peak memory recorded over runs, or `None` before the first.

    A read-only query: detection never writes state, and a database that is absent,
    locked, unreadable or not yet migrated simply yields no calibration.
    """
    if db is None or not db.exists():
        return None
    try:
        connection = sqlite3.connect(f"file:{db}?mode=ro", uri=True, timeout=5.0)
    except sqlite3.Error:  # pragma: no cover - only a malformed URI reaches this
        return None
    try:
        row = connection.execute("SELECT MAX(baseline_peak_mem_gb) FROM runs").fetchone()
    except sqlite3.Error:
        return None
    finally:
        connection.close()
    try:
        peak = float(row[0]) if row is not None and row[0] is not None else None
    except (TypeError, ValueError):
        return None
    return peak if peak is not None and peak > 0 else None


def overrides(ws: Workspace | None) -> tuple[int | None, float | None, int | None]:
    """The `[env]` overrides, if the workspace configuration carries any.

    Read by name rather than by field access, so a configuration without an `[env]`
    table, or with a field left unset, plans with the defaults instead of failing.
    """
    section = getattr(getattr(ws, "config", None), "env", None)
    return (
        _as_int(getattr(section, "reserved_cores", None)),
        _as_number(getattr(section, "reserved_mem_gb", None)),
        _as_int(getattr(section, "cores_per_lane", None)),
    )


def disk_free_gb(directory: Path) -> int:
    """Free space where the workspace lives, in whole GiB, rounded down; 0 if unknown."""
    try:
        return int(shutil.disk_usage(directory).free // host.GIB)
    except OSError:
        return 0


def engine_version() -> str:
    """The installed NautilusTrader version."""
    try:
        return importlib.metadata.version("nautilus_trader")
    except importlib.metadata.PackageNotFoundError:  # pragma: no cover - a hard dependency
        return host.UNKNOWN


def _now() -> str:
    """The detection timestamp: local wall-clock time with its UTC offset."""
    return datetime.now().astimezone().isoformat(timespec="seconds")


def _root(ws: Workspace | None) -> Path:
    root = getattr(ws, "root", None)
    return Path(root) if root is not None else Path.cwd()


def _path(ws: Workspace | None, name: str) -> Path | None:
    return None if ws is None else _root(ws) / name


def _as_number(value: object) -> float | None:
    """A number from an override, or `None` where it is unset or not one."""
    if isinstance(value, bool):
        return None
    if isinstance(value, int):
        return float(value)
    if isinstance(value, float) and math.isfinite(value):
        return value
    return None


def _as_int(value: object) -> int | None:
    """A whole number from an override, or `None` where it is unset or not a number."""
    number = _as_number(value)
    return None if number is None else int(number)
