"""The workspace data model: one pydantic model per file and per record kanso persists.

Every model refuses unknown fields, except the maps whose keys belong to somebody else —
a strategy's `config`, an instrument's `attributes` and `override`, a gate's `params` and
`evidence`. A failure raises `kanso.errors.ValidationError`, naming the field and the
reason, whether the model was built in Python or read from a file.

`load_yaml` and `dump_yaml` are the only ways these models reach and leave disk.
"""

from __future__ import annotations

from kanso.schemas.base import (
    SCHEMA_VERSION,
    CatalogueId,
    FreeForm,
    HypId,
    KansoModel,
    KansoRootModel,
    NonEmpty,
    Params,
    ParamValue,
    Sha256,
    Versioned,
)
from kanso.schemas.catalogue import (
    Applies,
    ConstructItem,
    CriteriaItem,
    DurationBounds,
    IntBounds,
    ParamType,
    RangeBound,
    parse_bound,
)
from kanso.schemas.certification import (
    Certificate,
    CertificationPlan,
    DataAvailability,
    EvaluatedGate,
    ExcludedGate,
    ObjectiveResult,
    PlanInputs,
    PlannedGate,
    Span,
    Verdict,
)
from kanso.schemas.duration import (
    DURATION_PATTERN,
    RESOLUTION_PATTERN,
    Duration,
    Resolution,
    is_duration,
    parse_duration,
    render_duration,
)
from kanso.schemas.envelope import Detected, Envelope, Plan
from kanso.schemas.hypothesis import (
    ConstraintRef,
    ConstructRef,
    DateWindow,
    Hypothesis,
    Mechanism,
    ObjectiveParams,
    ObjectiveRef,
    OpenWindow,
    RiskLimits,
    Windows,
    embargo,
    embargo_days,
)
from kanso.schemas.instruments import InstrumentEntry, InstrumentsFile, Resolved
from kanso.schemas.models import (
    ROUTING_DEFAULTS,
    TASK_CLASSES,
    TIERS,
    ModelsFile,
    ModelSpec,
    Route,
    Routing,
    RoutingEntry,
    TaskClass,
    Tier,
    check_tier_coverage,
)
from kanso.schemas.portfolio import Deployment, Limits, Portfolio, Stage, Stages
from kanso.schemas.run import (
    RESULTS_COLUMNS,
    RESULTS_HEADER,
    Card,
    CardStatus,
    GateResult,
    RunRecord,
)
from kanso.schemas.strategy import (
    AttachedRef,
    Expectation,
    Pins,
    SleeveRef,
    StrategyFile,
    StrategyVersion,
    VersionState,
)
from kanso.schemas.venue import (
    SANDBOX,
    Account,
    Costs,
    CostsOverride,
    ExecutionClientSpec,
    Origins,
    VenueDeclaration,
    VenueModel,
    VenueOverride,
    check_execution_client,
    resolve_venue_model,
    single_currency,
)
from kanso.schemas.yamlio import dump_yaml, load_yaml, parse_yaml, write_yaml

__all__ = [
    "DURATION_PATTERN",
    "RESOLUTION_PATTERN",
    "RESULTS_COLUMNS",
    "RESULTS_HEADER",
    "ROUTING_DEFAULTS",
    "SANDBOX",
    "SCHEMA_VERSION",
    "TASK_CLASSES",
    "TIERS",
    "Account",
    "Applies",
    "AttachedRef",
    "Card",
    "CardStatus",
    "CatalogueId",
    "Certificate",
    "CertificationPlan",
    "ConstraintRef",
    "ConstructItem",
    "ConstructRef",
    "Costs",
    "CostsOverride",
    "CriteriaItem",
    "DataAvailability",
    "DateWindow",
    "Deployment",
    "Detected",
    "Duration",
    "DurationBounds",
    "Envelope",
    "EvaluatedGate",
    "ExcludedGate",
    "ExecutionClientSpec",
    "Expectation",
    "FreeForm",
    "GateResult",
    "HypId",
    "Hypothesis",
    "InstrumentEntry",
    "InstrumentsFile",
    "IntBounds",
    "KansoModel",
    "KansoRootModel",
    "Limits",
    "Mechanism",
    "ModelSpec",
    "ModelsFile",
    "NonEmpty",
    "ObjectiveParams",
    "ObjectiveRef",
    "ObjectiveResult",
    "OpenWindow",
    "Origins",
    "ParamType",
    "ParamValue",
    "Params",
    "Pins",
    "Plan",
    "PlanInputs",
    "PlannedGate",
    "Portfolio",
    "RangeBound",
    "Resolution",
    "Resolved",
    "RiskLimits",
    "Route",
    "Routing",
    "RoutingEntry",
    "RunRecord",
    "Sha256",
    "SleeveRef",
    "Span",
    "Stage",
    "Stages",
    "StrategyFile",
    "StrategyVersion",
    "TaskClass",
    "Tier",
    "Verdict",
    "VenueDeclaration",
    "VenueModel",
    "VenueOverride",
    "Versioned",
    "VersionState",
    "Windows",
    "check_execution_client",
    "check_tier_coverage",
    "dump_yaml",
    "embargo",
    "embargo_days",
    "is_duration",
    "load_yaml",
    "parse_bound",
    "parse_duration",
    "parse_yaml",
    "render_duration",
    "resolve_venue_model",
    "single_currency",
    "write_yaml",
]
