"""Certifying a hypothesis that requires a custom data type.

A custom point read back from the catalog arrives inside the engine's `CustomData`, and a
certification runs in this process over the window it read, so the evidence gates are
shown the wrapped points and must group them by the type each one carries. A card never
met this: it pickles the window to a child and groups nothing. The subject here is a
perpetual held across its funding settlements on a continuous calendar — `bar` and
`funding`, both generated by the `synthetic` loader and written as `kanso data load`
writes them — so the certification window holds a custom type beside its bars.
"""

from __future__ import annotations

from datetime import date
from typing import Any

import pytest
import yaml

from kanso.certify import certificate, run
from kanso.certify.run import certify
from kanso.data import catalog, snapshot
from kanso.data.instruments import resolve_universe
from kanso.data.loaders.synthetic import SyntheticLoader
from kanso.data.manifest import catalog_path
from kanso.nautilus import backtest
from kanso.schemas import Costs, Hypothesis, VenueModel, resolve_venue_model
from kanso.schemas.venue import VenueDeclaration
from kanso.state import StateStore
from kanso.workspace import Workspace, find
from tests.research.conftest import classify, document

from .test_run import a_card, write_plan

PERP = "BTCUSDT-PERP.SIM"
HYP_ID = "perp_hold"
SERVED = (date(2024, 1, 1), date(2024, 1, 31))
"""The month the catalog holds: hourly bars and three settlements a day, every day."""

RESEARCH = (date(2024, 1, 1), date(2024, 1, 10))
CERTIFICATION = (date(2024, 1, 15), date(2024, 1, 25))

SPEC: dict[str, Any] = {
    "loader": "synthetic",
    "model": "gbm",
    "seed": 7,
    "instruments": ["BTCUSDT-PERP"],
    "venue": "SIM",
    "resolution": "1h",
    "types": ["bar", "funding"],
    "calendar": "continuous",
    "start": SERVED[0],
    "end": SERVED[1],
    "start_price": 40_000.0,
    "sigma_bps": 20.0,
    "price_precision": 1,
}
"""The loader spec `kanso data load` would be handed for the perpetual."""

ENTRY: dict[str, Any] = {
    "nautilus_id": PERP,
    "asset_class": "CRYPTOCURRENCY",
    "manual": True,
    "corporate_actions": "none",
    "override": {
        "instrument_class": "swap",
        "base_currency": "BTC",
        "quote_currency": "USDT",
        "settlement_currency": "USDT",
        "multiplier": "0.01",
        "price_increment": "0.1",
        "size_increment": "1",
        "lot_size": "1",
    },
}
"""The manual linear perpetual `docs/workspace.md` shows."""

HOLDING = b'''
from kanso.nautilus.strategy import KansoConfig, KansoStrategy


class Config(KansoConfig):
    enter: int = 5
    leave: int = 60


class Strategy(KansoStrategy):
    """Buys ten contracts on the fifth hourly bar and closes them on the sixtieth, so the
    position is held through several settlements of every window."""

    config_cls = Config

    def on_start(self):
        self.seen = 0

    def on_bar(self, bar):
        self.seen += 1
        if self.seen == self.kanso_config.enter:
            self.submit_entry(bar.bar_type.instrument_id, "BUY", qty=10)
        elif self.seen == self.kanso_config.leave:
            self.submit_exit(bar.bar_type.instrument_id)
'''

DOCUMENT = document(
    id=HYP_ID,
    title="A perpetual held across funding settlements",
    thesis="A long perpetual held for days pays and is paid the realised rate at every settlement.",
    mechanism="momentum",
    universe=[PERP],
    resolution="1h",
    data_requirements=["bar", "funding"],
    windows={
        "research": {"start": RESEARCH[0], "end": RESEARCH[1]},
        "certification": {"start": CERTIFICATION[0], "end": CERTIFICATION[1]},
        "forward": {"start": date(2024, 1, 29)},
    },
)
"""The demo hypothesis re-pointed at the perpetual: a sleeve requiring a custom type."""


def perp_model() -> VenueModel:
    """The model the hypothesis's costs resolve to on the perpetual's USDT venue."""
    return resolve_venue_model(
        "SIM",
        config=VenueDeclaration(currency="USDT"),
        broker="synthetic",
        hypothesis_costs=Costs.model_validate(DOCUMENT["costs"]),
        max_leverage=1.0,
        quotes_available=False,
    )


@pytest.fixture
def perp_ws(ws: Workspace) -> Workspace:
    """The demo workspace with the perpetual loaded beside its equity.

    A USDT account, the manual entry resolved, the month of bars and settlements written
    dataset by dataset as `kanso data load` writes a loader's discoveries, and a snapshot
    frozen over all of it.
    """
    config = ws.path("kanso.toml")
    config.write_text(
        config.read_text(encoding="utf-8").replace('currency = "USD"', 'currency = "USDT"'),
        encoding="utf-8",
    )
    instruments = ws.path("instruments.yaml")
    entries = yaml.safe_load(instruments.read_text(encoding="utf-8"))
    entries[PERP] = ENTRY
    instruments.write_text(yaml.safe_dump(entries, sort_keys=False), encoding="utf-8")
    ws = find(ws.root)
    resolve_universe(ws, [PERP], SERVED[0])
    loader = SyntheticLoader()
    for ref in loader.discover(SPEC):
        catalog.write(ws, list(loader.load(ref, ref.span)), ref=ref, source="synthetic")
    snapshot.freeze(ws)
    return ws


def test_a_hypothesis_requiring_a_custom_type_is_certified_over_the_points_the_catalog_wraps(
    perp_ws: Workspace, store: StateStore
) -> None:
    classify(perp_ws, store, DOCUMENT, HOLDING)
    sha = a_card(perp_ws, store, HOLDING, hyp_id=HYP_ID, document=DOCUMENT, model=perp_model())
    write_plan(perp_ws, HYP_ID)

    made = certify(perp_ws, store, HYP_ID)

    assert made.verdict == "pass", [(gate.id, gate.evidence) for gate in made.gates]
    assert made.strategy_sha == sha
    assert certificate.certificate_file(perp_ws, made).is_file()
    (lag,) = [gate for gate in made.gates if gate.id == "publication_lag"]
    assert lag.skipped is None, "the gate was shown the window, settlements included"
    assert lag.passed, "a settlement is published at the instant it settles"


def test_the_lags_a_certification_observes_are_grouped_by_the_type_a_wrapped_point_carries(
    perp_ws: Workspace,
) -> None:
    """The window the certifier reads holds the settlements inside the catalog's wrapper,
    and the evidence it takes is keyed by the type inside: `funding`, settled at the
    instant it was published, beside the bars."""
    request = backtest.RunRequest(
        hyp=Hypothesis.model_validate(DOCUMENT),
        strategy_source=HOLDING,
        window=CERTIFICATION,
        snapshot_id="a" * 64,
        venue_model=perp_model().model_dump(),
        capital=100_000.0,
    )
    _, groups = backtest.window_data(request, catalog_path(perp_ws))

    observed = run._observed_lags(groups)

    assert set(observed) == {(PERP, "bar"), (PERP, "funding")}
    assert observed[(PERP, "funding")] == 0.0
